package com.terry.es.mapper;

import com.terry.es.entity.Article;

import java.util.List;

public interface ArticleMapper {

    List<Article> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMF_FND_ARTICLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMF_FND_ARTICLE
     *
     * @mbggenerated
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMF_FND_ARTICLE
     *
     * @mbggenerated
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMF_FND_ARTICLE
     *
     * @mbggenerated
     */
    Article selectByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMF_FND_ARTICLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CMF_FND_ARTICLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Article record);
}
